/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

/**
 *
 * @author User
 */
import Negocio.Control.Persona;
import Negocio.Modelo.Agenda;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;

public class InterfazFormulario extends javax.swing.JFrame {
    javax.swing.ImageIcon icono = new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes/Aprobado.png"));

    
    public InterfazFormulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JLNombres = new javax.swing.JLabel();
        JLApellidos = new javax.swing.JLabel();
        JLCI = new javax.swing.JLabel();
        JLEmail = new javax.swing.JLabel();
        JLTelefono = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtCI = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtValidador = new javax.swing.JTextField();
        BotonGuardar = new javax.swing.JButton();
        BotonLimpiar = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        JLImagenNombres = new javax.swing.JLabel();
        JLImagenApellidos = new javax.swing.JLabel();
        JLImagenCI = new javax.swing.JLabel();
        JLImagenEmail = new javax.swing.JLabel();
        JLImagenTelefono = new javax.swing.JLabel();
        BotonMostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Formulacion de Datos");

        JLNombres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JLNombres.setForeground(new java.awt.Color(255, 255, 0));
        JLNombres.setText("Nombres");

        JLApellidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JLApellidos.setForeground(new java.awt.Color(255, 255, 0));
        JLApellidos.setText("Apellidos");

        JLCI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JLCI.setForeground(new java.awt.Color(255, 255, 0));
        JLCI.setText("CI");

        JLEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JLEmail.setForeground(new java.awt.Color(255, 255, 0));
        JLEmail.setText("Email");

        JLTelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JLTelefono.setForeground(new java.awt.Color(255, 255, 0));
        JLTelefono.setText("Telefono");

        txtNombres.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombresFocusLost(evt);
            }
        });
        txtNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombresKeyTyped(evt);
            }
        });

        txtApellidos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApellidosFocusLost(evt);
            }
        });
        txtApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidosKeyTyped(evt);
            }
        });

        txtCI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCIFocusLost(evt);
            }
        });
        txtCI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCIKeyTyped(evt);
            }
        });

        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailKeyTyped(evt);
            }
        });

        txtTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelefonoFocusLost(evt);
            }
        });
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        txtValidador.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValidadorFocusLost(evt);
            }
        });
        txtValidador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValidadorKeyTyped(evt);
            }
        });

        BotonGuardar.setText("Guardar");
        BotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarActionPerformed(evt);
            }
        });

        BotonLimpiar.setText("Limpiar");
        BotonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLimpiarActionPerformed(evt);
            }
        });

        BotonSalir.setText("Salir");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        JLImagenNombres.setMaximumSize(new java.awt.Dimension(20, 20));
        JLImagenNombres.setMinimumSize(new java.awt.Dimension(20, 20));
        JLImagenNombres.setPreferredSize(new java.awt.Dimension(20, 20));

        JLImagenApellidos.setMaximumSize(new java.awt.Dimension(20, 20));
        JLImagenApellidos.setMinimumSize(new java.awt.Dimension(20, 20));
        JLImagenApellidos.setPreferredSize(new java.awt.Dimension(20, 20));

        JLImagenCI.setMaximumSize(new java.awt.Dimension(20, 20));
        JLImagenCI.setMinimumSize(new java.awt.Dimension(20, 20));
        JLImagenCI.setPreferredSize(new java.awt.Dimension(20, 20));

        JLImagenEmail.setMaximumSize(new java.awt.Dimension(20, 20));
        JLImagenEmail.setMinimumSize(new java.awt.Dimension(20, 20));
        JLImagenEmail.setPreferredSize(new java.awt.Dimension(20, 20));

        JLImagenTelefono.setMaximumSize(new java.awt.Dimension(20, 20));
        JLImagenTelefono.setMinimumSize(new java.awt.Dimension(20, 20));
        JLImagenTelefono.setPreferredSize(new java.awt.Dimension(20, 20));

        BotonMostrar.setText("Mostrar");
        BotonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JLApellidos)
                            .addComponent(JLNombres)
                            .addComponent(JLCI)
                            .addComponent(JLEmail)
                            .addComponent(JLTelefono)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BotonMostrar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombres)
                            .addComponent(txtApellidos)
                            .addComponent(txtEmail)
                            .addComponent(txtTelefono)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCI, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValidador, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(BotonGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLImagenEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLImagenTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLImagenApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLImagenNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLImagenCI, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLNombres)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLImagenNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLImagenApellidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JLApellidos)
                        .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLImagenCI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JLCI)
                        .addComponent(txtCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtValidador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLImagenEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JLEmail)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLImagenTelefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JLTelefono)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonGuardar)
                    .addComponent(BotonLimpiar)
                    .addComponent(BotonSalir)
                    .addComponent(BotonMostrar))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        FondoFormulario AplicarFondo = new FondoFormulario();
        
        this.add( AplicarFondo , BorderLayout.SOUTH);
        AplicarFondo.repaint();
    }//GEN-LAST:event_formWindowOpened

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        // TODO add your handling code here:
        if(txtTelefono.getText().length()>=7){
            evt.consume();
        }
        char TipoDeTecla = evt.getKeyChar();
        if(!Character.isDigit(TipoDeTecla)){
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefonoFocusLost
        // TODO add your handling code here:
        if(txtTelefono.getText().length()>=2){
            JLImagenTelefono.setIcon(icono);
        }
        else{
            JLImagenTelefono.setIcon(null);
        }
    }//GEN-LAST:event_txtTelefonoFocusLost

    private void txtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyTyped
        // TODO add your handling code here:
        if(txtEmail.getText().length()>=24){
            evt.consume();
        }
        char TipoDeTecla = evt.getKeyChar();
        if(Character.isDigit(TipoDeTecla)){
            evt.consume();
        }
    }//GEN-LAST:event_txtEmailKeyTyped

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        // TODO add your handling code here:
        if(txtEmail.getText().length()>=2){
            JLImagenEmail.setIcon(icono);
        }
        else{
            JLImagenEmail.setIcon(null);
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtValidadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValidadorKeyTyped
        // TODO add your handling code here:
        if(txtValidador.getText().length()==1){
            evt.consume();
        }
        char TipoDeTecla = evt.getKeyChar();
        if(!Character.isDigit(TipoDeTecla)){
            evt.consume();
        }
    }//GEN-LAST:event_txtValidadorKeyTyped

    private void txtValidadorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValidadorFocusLost
        // TODO add your handling code here:
        if(txtValidador.getText().length()>=1){
            JLImagenCI.setIcon(icono);
        }
        else{
            JLImagenCI.setIcon(null);
        }
    }//GEN-LAST:event_txtValidadorFocusLost

    private void txtCIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCIKeyTyped
        // TODO add your handling code here:
        if(txtCI.getText().length()>=9){
            evt.consume();
        }
        char TipoDeTecla = evt.getKeyChar();
        if(!Character.isDigit(TipoDeTecla)){
            evt.consume();
        }
    }//GEN-LAST:event_txtCIKeyTyped

    private void txtCIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCIFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_txtCIFocusLost

    private void txtApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosKeyTyped
        // TODO add your handling code here:
        if(txtApellidos.getText().length()>=24){
            evt.consume();
        }
        char TipoDeTecla = evt.getKeyChar();
        if(Character.isDigit(TipoDeTecla)){
            evt.consume();
        }
    }//GEN-LAST:event_txtApellidosKeyTyped

    private void txtApellidosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidosFocusLost
        // TODO add your handling code here:
        if(txtApellidos.getText().length()>=2){
            JLImagenApellidos.setIcon(icono);
        }
        else{
            JLImagenApellidos.setIcon(null);
        }
    }//GEN-LAST:event_txtApellidosFocusLost

    private void txtNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyTyped
        // TODO add your handling code here:
        if(txtNombres.getText().length()>=23){
            evt.consume();
        }
        char TipoDeTecla = evt.getKeyChar();
        if(Character.isDigit(TipoDeTecla)){
            evt.consume();
        }
    }//GEN-LAST:event_txtNombresKeyTyped

    private void txtNombresFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombresFocusLost
        // TODO add your handling code here:
        if(txtNombres.getText().length()>=2){
            JLImagenNombres.setIcon(icono);
        }
        else{
            JLImagenNombres.setIcon(null);
        }
    }//GEN-LAST:event_txtNombresFocusLost

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void BotonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLimpiarActionPerformed
        // TODO add your handling code here:
        txtNombres.setText("");
        txtApellidos.setText("");
        txtCI.setText("");
        txtValidador.setText("");
        txtEmail.setText("");
        txtTelefono.setText("");
    }//GEN-LAST:event_BotonLimpiarActionPerformed

    private void BotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarActionPerformed
        // TODO add your handling code here:
        if(txtNombres.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Por favor ingrese los Nombres");
            return;
        }
        if(txtApellidos.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Por favor ingrese los Apellidos");
            return;
        }
        if(txtCI.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Por favor ingrese Cedula de Identidad");
            return;
        }
        if(txtValidador.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Por favor ingrese validador");
            return;
        }
        if(txtEmail.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Por favor ingrese Validador");
            return;
        }
        if(txtTelefono.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Por favor ingrse el Telefono");
            return;
        }
        //Limpiaremos un poco el codigo haciendo variables nuevas
        String Nombres,Apellidos,CI,Validador,Email,Telefono;
        //Los llenaremos con las variables
        Nombres = txtNombres.getText();
        Apellidos = txtApellidos.getText();
        CI = txtCI.getText();
        Validador = txtValidador.getText();
        Email = txtEmail.getText();
        Telefono = txtTelefono.getText();

        // y aqui nuestra respuesta de los datos bien agregados
        Persona persona = new Persona(Nombres,Apellidos,CI,Email,Telefono);
        Agenda agenda = new Angenda();
        agenda.GuardarPersona(persona);
    }//GEN-LAST:event_BotonGuardarActionPerformed

    private void BotonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMostrarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, agenda.MostrarAgenda());
    }//GEN-LAST:event_BotonMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazFormulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonGuardar;
    private javax.swing.JButton BotonLimpiar;
    private javax.swing.JButton BotonMostrar;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JLabel JLApellidos;
    private javax.swing.JLabel JLCI;
    private javax.swing.JLabel JLEmail;
    private javax.swing.JLabel JLImagenApellidos;
    private javax.swing.JLabel JLImagenCI;
    private javax.swing.JLabel JLImagenEmail;
    private javax.swing.JLabel JLImagenNombres;
    private javax.swing.JLabel JLImagenTelefono;
    private javax.swing.JLabel JLNombres;
    private javax.swing.JLabel JLTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCI;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtValidador;
    // End of variables declaration//GEN-END:variables
}
